import pickle
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
import pandas as pd

SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly']

# Reference: https://developers.google.com/sheets/api/quickstart/python
def read_google_sheets(SPREADSHEET_ID, RANGE_NAME, HEADER_RANGE):
    creds = None
    # autogenerated
    if os.path.exists('token.pickle'):
        with open('token.pickle', 'rb') as token:
            creds = pickle.load(token)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)

    service = build('sheets', 'v4', credentials=creds)

    sheet = service.spreadsheets()
    result = sheet.values().get(spreadsheetId=SPREADSHEET_ID,
                                range=RANGE_NAME).execute()
    
    header = sheet.values().get(spreadsheetId=SPREADSHEET_ID,
                               range=HEADER_RANGE).execute()
    
    header_values = header.get('values', [])
    values = result.get('values', [])
    
    return values, header_values

def main():
    # variable_metadata = pd.read_csv("etc/variables.csv")

    # Data sheet
    print("Downloading data into data.csv")
    SPREADSHEET_ID = '1ihrTZwDq744Piqyb2u-OBLf_zmcQr33XFdUBiDzeREU'
    RANGE_NAME = "'US–wide'!A2:Y"
    HEADER_RANGE = "'US–wide'!A1:Y1"
    data, header = read_google_sheets(SPREADSHEET_ID, RANGE_NAME, HEADER_RANGE)
    data_df = pd.DataFrame(data, columns = header[0])
    data_df.to_csv('raw/data.csv', index=False)
    print("successful")

    # # Song metadata sheet
    print("Downloading ensembles metadata into metadata.csv")
    SPREADSHEET_ID = '1RvYJbzTd7fH6FoQl9TC-BYVwxUl0E4ae6WXVMdAcIow'
    RANGE_NAME = "'Sheet1'!A2:AS"
    HEADER_RANGE = "'Sheet1'!A1:AS1"
    data, header = read_google_sheets(SPREADSHEET_ID, RANGE_NAME, HEADER_RANGE)
    metadata_df = pd.DataFrame(data, columns = header[0])
    metadata_df.to_csv('raw/metadata.csv', index=False)
    print("successful")

main()
